version: '3.1'

services:
  suucuri:
    build: .
    command: python3 -m wsgi --port=8575
    restart: always
    environment:
      - VIRTUAL_HOST=horacio.nce.ufrj.br
      - VIRTUAL_PORT=8575
    ports:
      - "8575:8575"
