version: '3.1'

services:
  suucuri:
    build: .
    command: python3 -m wsgi --port=8665
    restart: always
    environment:
      - VIRTUAL_HOST=afetora.ydns.eu
      - VIRTUAL_PORT=8665
    ports:
      - "8665:8665"
